"""
report_builder.py — QShield PDF Report Generation Service
==========================================================

Generates professional PDF reports directly from structured data using ReportLab.

Three report generators (called by router endpoints and ZIP bundle):
  - build_executive_pdf(data: dict) -> bytes
  - build_inventory_pdf(data: dict) -> bytes
  - build_roadmap_pdf(data: dict)   -> bytes

Each returns PDF bytes.  The caller writes to a streaming response or ZIP buffer.

Design principles:
  - Pure function: takes structured data dict, returns PDF bytes.
  - No DB access — data is pre-loaded by the router, which reuses existing engines.
  - No LLM. No score recalculation. No fake data.
  - Secrets / private keys are never passed into these functions (router is responsible).
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, PageBreak
)
from reportlab.platypus.flowables import Flowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

# ── Brand colours ─────────────────────────────────────────────────────────────
C_INK      = HexColor("#192837")      # deep navy text
C_ACCENT   = HexColor("#7342E2")      # QShield purple
C_SURF     = HexColor("#ffffff")
C_BG       = HexColor("#F2F2EE")      # off-white bg
C_BORDER   = HexColor("#e2e8f0")

C_CRIT     = HexColor("#ef4444")      # severity: Critical
C_HIGH     = HexColor("#f97316")      # severity: High
C_MOD      = HexColor("#eab308")      # severity: Moderate
C_LOW      = HexColor("#22c55e")      # severity: Low
C_SAFE     = HexColor("#10b981")      # quantum-safe
C_MUTED    = HexColor("#94a3b8")

PAGE_W, PAGE_H = A4


# ── Severity helpers ──────────────────────────────────────────────────────────

def _sev_color(sev: str) -> HexColor:
    s = (sev or "").lower()
    return {
        "critical": C_CRIT,
        "high":     C_HIGH,
        "moderate": C_MOD,
        "medium":   C_MOD,
        "low":      C_LOW,
        "safe":     C_SAFE,
    }.get(s, C_MUTED)


def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ── Shared page callbacks ─────────────────────────────────────────────────────

def _make_page_callbacks(report_title: str, project_name: str):
    """Returns (on_first_page, on_later_pages) for ReportLab page templates."""

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(C_MUTED)
        left = doc.leftMargin
        right = PAGE_W - doc.rightMargin
        y = 12 * mm

        canvas.drawString(left, y, f"Generated by QShield  |  {report_title}")
        canvas.drawRightString(right, y, f"Page {doc.page}")
        # thin rule
        canvas.setStrokeColor(C_BORDER)
        canvas.setLineWidth(0.4)
        canvas.line(left, y + 4 * mm, right, y + 4 * mm)
        canvas.restoreState()

    def on_first_page(canvas, doc):
        _footer(canvas, doc)

    def on_later_pages(canvas, doc):
        _footer(canvas, doc)

    return on_first_page, on_later_pages


# ── Style registry ─────────────────────────────────────────────────────────────

def _styles():
    base = getSampleStyleSheet()
    s = {
        "h1": ParagraphStyle(
            "QS_H1", fontName="Helvetica-Bold", fontSize=18,
            textColor=C_INK, spaceAfter=6, spaceBefore=4,
        ),
        "h2": ParagraphStyle(
            "QS_H2", fontName="Helvetica-Bold", fontSize=13,
            textColor=C_ACCENT, spaceAfter=4, spaceBefore=10,
            borderPad=(0, 0, 3, 0),
        ),
        "h3": ParagraphStyle(
            "QS_H3", fontName="Helvetica-Bold", fontSize=10,
            textColor=C_INK, spaceAfter=3, spaceBefore=6,
        ),
        "body": ParagraphStyle(
            "QS_Body", fontName="Helvetica", fontSize=9,
            textColor=C_INK, spaceAfter=3, leading=14,
        ),
        "small": ParagraphStyle(
            "QS_Small", fontName="Helvetica", fontSize=8,
            textColor=C_MUTED, spaceAfter=2, leading=12,
        ),
        "caption": ParagraphStyle(
            "QS_Caption", fontName="Helvetica-Oblique", fontSize=8,
            textColor=C_MUTED, spaceAfter=4, alignment=TA_CENTER,
        ),
        "disclaimer": ParagraphStyle(
            "QS_Disc", fontName="Helvetica-Oblique", fontSize=8,
            textColor=C_MUTED, spaceAfter=3, leading=12,
            backColor=HexColor("#f8f8f5"),
            borderColor=C_BORDER, borderWidth=0.5,
            borderPad=6,
        ),
        "cover_title": ParagraphStyle(
            "QS_CoverTitle", fontName="Helvetica-Bold", fontSize=26,
            textColor=C_SURF, spaceAfter=8, alignment=TA_CENTER,
        ),
        "cover_sub": ParagraphStyle(
            "QS_CoverSub", fontName="Helvetica", fontSize=13,
            textColor=HexColor("#cbd5e1"), spaceAfter=4, alignment=TA_CENTER,
        ),
        "cover_meta": ParagraphStyle(
            "QS_CoverMeta", fontName="Helvetica", fontSize=10,
            textColor=HexColor("#94a3b8"), spaceAfter=3, alignment=TA_CENTER,
        ),
    }
    return s


# ── Table style helpers ───────────────────────────────────────────────────────

_BASE_TABLE = TableStyle([
    ("BACKGROUND",  (0, 0), (-1, 0),  C_INK),
    ("TEXTCOLOR",   (0, 0), (-1, 0),  C_SURF),
    ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
    ("FONTSIZE",    (0, 0), (-1, 0),  8),
    ("ALIGN",       (0, 0), (-1, 0),  "CENTER"),
    ("BOTTOMPADDING", (0, 0), (-1, 0), 5),
    ("TOPPADDING",    (0, 0), (-1, 0), 5),
    ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
    ("FONTSIZE",    (0, 1), (-1, -1), 8),
    ("TEXTCOLOR",   (0, 1), (-1, -1), C_INK),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_SURF, HexColor("#f8f8f5")]),
    ("GRID",        (0, 0), (-1, -1), 0.3, C_BORDER),
    ("TOPPADDING",  (0, 1), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
])


def _table(data: list[list], col_widths: list[float] | None = None,
           extra_style: list | None = None) -> Table:
    ts = TableStyle(_BASE_TABLE.getCommands())
    if extra_style:
        ts.add(*extra_style) if len(extra_style) == 3 else [ts.add(*cmd) for cmd in extra_style]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(ts)
    return t


# ── Cover page builder ────────────────────────────────────────────────────────

class _ColorRect(Flowable):
    """Solid colour rectangle that fills the page — used as cover background."""
    def __init__(self, w, h, fill):
        super().__init__()
        self.width, self.height, self.fill = w, h, fill

    def draw(self):
        self.canv.setFillColor(self.fill)
        self.canv.rect(0, 0, self.width, self.height, fill=1, stroke=0)


def _cover_flows(report_title: str, subtitle: str,
                 scan_name: str, project_name: str, app_name: str,
                 generated_at: str, version: str = "v1.0") -> list:
    s = _styles()
    usable_w = PAGE_W - 4 * cm  # approximate

    flows: list = []
    # dark background slab
    flows.append(Spacer(1, 3 * cm))
    flows.append(Paragraph("QShield", ParagraphStyle(
        "QSBrand", fontName="Helvetica-Bold", fontSize=11,
        textColor=C_ACCENT, spaceAfter=2, alignment=TA_CENTER,
    )))
    flows.append(Spacer(1, 0.5 * cm))
    flows.append(Paragraph(report_title, s["cover_title"]))
    flows.append(Spacer(1, 0.3 * cm))
    flows.append(Paragraph(subtitle, s["cover_sub"]))
    flows.append(Spacer(1, 1.5 * cm))

    # Meta table
    meta = [
        ["Project",   project_name or "—"],
        ["Application", app_name or "—"],
        ["Scan",       scan_name or "—"],
        ["Generated",  generated_at],
        ["Version",    version],
    ]
    meta_t = Table(meta, colWidths=[4 * cm, 11 * cm])
    meta_t.setStyle(TableStyle([
        ("FONTNAME",  (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",  (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",  (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, -1), HexColor("#cbd5e1")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("LINEBELOW",  (0, 0), (-1, -1), 0.3, HexColor("#334155")),
    ]))

    # wrap in a solid-bg card
    flows.append(meta_t)
    flows.append(Spacer(1, 1 * cm))
    flows.append(Paragraph(
        "CONFIDENTIAL — For authorised recipients only. QShield internal metrics "
        "are not official NIST scores or compliance certifications.",
        s["disclaimer"],
    ))
    return flows


# ═══════════════════════════════════════════════════════════════════════════════
# REPORT 1: Executive Quantum Readiness
# ═══════════════════════════════════════════════════════════════════════════════

def build_executive_pdf(data: dict) -> bytes:
    """
    Build Executive Quantum Readiness Report PDF.

    data keys expected (from /api/reports/executive JSON):
      scan, dashboard (DashboardSummary dict), recommendations (list)
    """
    buf = io.BytesIO()
    s = _styles()
    usable_w = PAGE_W - 4 * cm

    dash   = data.get("dashboard", {})
    recs   = data.get("recommendations", [])
    scan   = data.get("scan", {})
    proj   = data.get("project", {})

    project_name = proj.get("name") or dash.get("application_name", "—")
    app_name     = dash.get("application_name", "—")
    scan_name    = dash.get("scan_name", "—")
    gen_ts       = _now_utc()
    qrs          = dash.get("quantum_readiness_score", 0)
    rl           = dash.get("readiness_label", "—")

    on_first, on_later = _make_page_callbacks("Executive Quantum Readiness Report", project_name)

    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2.5*cm,
        title="Executive Quantum Readiness Report",
        author="QShield",
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin,
                  doc.width, doc.height, id="normal")
    doc.addPageTemplates([
        PageTemplate(id="main", frames=frame,
                     onPage=on_first, onPageEnd=on_later),
    ])

    story = []

    # ── Cover ─────────────────────────────────────────────────────────────────
    story += _cover_flows(
        "Executive Quantum\nReadiness Report",
        "Quantum Cryptography Posture Assessment",
        scan_name, project_name, app_name, gen_ts,
    )
    story.append(PageBreak())

    # ── 1. Executive Summary ──────────────────────────────────────────────────
    story.append(Paragraph("1. Executive Summary", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    total = dash.get("total_findings", 0)
    qrelf = dash.get("quantum_relevant_findings", 0)
    crit  = dash.get("critical_findings", 0)
    high  = dash.get("high_findings", 0)
    prog  = dash.get("migration_progress_pct", 0.0)

    story.append(Paragraph(
        f"This report summarises the quantum cryptography posture of <b>{app_name}</b> "
        f"based on scan <i>{scan_name}</i>. A total of <b>{total}</b> cryptographic findings "
        f"were identified, of which <b>{qrelf}</b> are quantum-migration relevant. "
        f"The organisation's current Quantum Readiness Score is <b>{qrs}/100</b> "
        f"({rl}). Migration is <b>{prog:.1f}%</b> complete as measured by weighted roadmap stage progress.",
        s["body"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    # ── 2. Quantum Readiness Score ────────────────────────────────────────────
    story.append(Paragraph("2. Quantum Readiness Score", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    meth = dash.get("readiness_methodology", {})
    score_data = [
        ["Component", "Weight", "Value", "Contribution"],
        ["Exposure (non-vulnerable / total)", "60%",
         f"{meth.get('s_exposure', 0):.4f}",
         f"{meth.get('s_exposure', 0)*60:.1f}"],
        ["Risk Inversion (1 − avg_risk/100)", "25%",
         f"{meth.get('s_risk_inv', 0):.4f}",
         f"{meth.get('s_risk_inv', 0)*25:.1f}"],
        ["Migration Progress (migrated/total)", "15%",
         f"{meth.get('s_progress', 0):.4f}",
         f"{meth.get('s_progress', 0)*15:.1f}"],
        ["TOTAL SCORE", "100%", "—", str(qrs)],
    ]
    score_col_w = [9*cm, 2*cm, 2.5*cm, 2.5*cm]
    score_t = Table(score_data, colWidths=score_col_w, repeatRows=1)
    score_t.setStyle(TableStyle(
        _BASE_TABLE.getCommands() + [
            ("BACKGROUND", (0, 4), (-1, 4), C_ACCENT),
            ("TEXTCOLOR",  (0, 4), (-1, 4), C_SURF),
            ("FONTNAME",   (0, 4), (-1, 4), "Helvetica-Bold"),
        ]
    ))
    story.append(score_t)
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        meth.get("disclaimer",
            "The Quantum Readiness Score is an internal deterministic prioritization metric "
            "derived from cryptographic exposure, migration risk, and migration progress. "
            "It is intended for planning purposes and is not an official NIST score."),
        s["disclaimer"],
    ))
    story.append(Spacer(1, 0.4 * cm))

    # ── 3. Overall Risk Summary ───────────────────────────────────────────────
    story.append(Paragraph("3. Overall Risk Summary", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    risk_data = [
        ["Metric", "Value"],
        ["Total Findings",             str(total)],
        ["Quantum-Relevant Findings",  str(qrelf)],
        ["Quantum-Safe Findings",      str(dash.get("quantum_safe_findings", 0))],
        ["Critical Severity",          str(crit)],
        ["High Severity",              str(high)],
        ["Moderate Severity",          str(dash.get("moderate_findings", 0))],
        ["Low Severity",               str(dash.get("low_findings", 0))],
        ["Migration Progress",         f"{prog:.1f}%"],
        ["Migrated Items",             str(dash.get("migrated_items", 0))],
        ["Total Roadmap Items",        str(dash.get("total_roadmap_items", 0))],
    ]
    risk_t = Table(risk_data, colWidths=[11*cm, 5*cm], repeatRows=1)
    extra = []
    for i, (label, val) in enumerate(risk_data[1:], start=1):
        if "Critical" in label and int(val or 0) > 0:
            extra.append(("BACKGROUND", (1, i), (1, i), C_CRIT))
            extra.append(("TEXTCOLOR",  (1, i), (1, i), C_SURF))
        elif "High" in label and int(val or 0) > 0:
            extra.append(("BACKGROUND", (1, i), (1, i), C_HIGH))
            extra.append(("TEXTCOLOR",  (1, i), (1, i), C_SURF))
    risk_t.setStyle(TableStyle(_BASE_TABLE.getCommands() + extra))
    story.append(risk_t)
    story.append(Spacer(1, 0.4 * cm))

    # ── 4. Algorithm Distribution ─────────────────────────────────────────────
    algo_dist = dash.get("algorithm_distribution", [])
    if algo_dist:
        story.append(Paragraph("4. Algorithm Distribution", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
        algo_rows = [["Algorithm Family", "Findings"]]
        for a in algo_dist:
            algo_rows.append([a.get("family", "—"), str(a.get("count", 0))])
        story.append(_table(algo_rows, col_widths=[13*cm, 3*cm]))
        story.append(Spacer(1, 0.4 * cm))

    # ── 5. Top Risk Findings ──────────────────────────────────────────────────
    top_findings = dash.get("top_findings", [])
    if top_findings:
        story.append(Paragraph("5. Top Risk Findings", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
        tf_rows = [["Algorithm", "Family", "File", "Risk Score", "Severity"]]
        tf_extra = []
        for i, f in enumerate(top_findings, start=1):
            sev = f.get("severity", "Low")
            fpath = (f.get("file_path") or "—")[-50:]  # truncate long paths
            tf_rows.append([
                f.get("algorithm", "—"),
                f.get("algorithm_family", "—"),
                fpath,
                str(f.get("risk_score", 0)),
                sev,
            ])
            tf_extra.append(("TEXTCOLOR", (4, i), (4, i), _sev_color(sev)))
            tf_extra.append(("FONTNAME",  (4, i), (4, i), "Helvetica-Bold"))

        story.append(_table(
            tf_rows,
            col_widths=[3*cm, 3*cm, 6*cm, 2.5*cm, 2.5*cm],
            extra_style=tf_extra if tf_extra else None,
        ))
        story.append(Spacer(1, 0.4 * cm))

    # ── 6. Migration Waves ────────────────────────────────────────────────────
    wave_dist = dash.get("wave_distribution", [])
    stage_dist = dash.get("stage_distribution", [])
    if wave_dist or stage_dist:
        story.append(Paragraph("6. Migration Progress", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
        if wave_dist:
            wave_rows = [["Wave", "Label", "Items"]]
            for w in wave_dist:
                wave_rows.append([str(w.get("wave", "—")), w.get("label", "—"), str(w.get("count", 0))])
            story.append(Paragraph("Migration Waves", s["h3"]))
            story.append(_table(wave_rows, col_widths=[2*cm, 8*cm, 6*cm]))
            story.append(Spacer(1, 0.3 * cm))
        if stage_dist:
            stg_rows = [["Stage", "Items"]]
            for st in stage_dist:
                stg_rows.append([st.get("stage", "—"), str(st.get("count", 0))])
            story.append(Paragraph("Lifecycle Stages", s["h3"]))
            story.append(_table(stg_rows, col_widths=[8*cm, 8*cm]))
            story.append(Spacer(1, 0.4 * cm))

    # ── 7. Executive Recommendations ─────────────────────────────────────────
    quantum_recs = [r for r in recs if r.get("is_quantum_concern")][:5]
    if quantum_recs:
        story.append(PageBreak())
        story.append(Paragraph("7. Executive Recommendations", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
        for i, r in enumerate(quantum_recs, 1):
            algo  = r.get("algorithm", "—")
            tgt   = r.get("recommended_target_category", "Manual Review")
            prio  = r.get("migration_priority", "low").upper()
            stds  = ", ".join(r.get("nist_standards", [])) or "—"
            steps = r.get("migration_steps", [])[:3]
            story.append(KeepTogether([
                Paragraph(f"{i}. {algo} → {tgt}  [Priority: {prio}]", s["h3"]),
                Paragraph(r.get("current_state_description", ""), s["body"]),
                Paragraph(f"NIST Standards: {stds}", s["small"]),
                *(Paragraph(f"• {step}", s["body"]) for step in steps),
                Spacer(1, 0.2 * cm),
            ]))

    # ── 8. Limitations ────────────────────────────────────────────────────────
    story.append(Paragraph("8. Limitations", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
    for note in [
        "QShield Quantum Readiness Scores are internal deterministic prioritization metrics — not official NIST scores or compliance certifications.",
        "Cryptographic findings are identified by static analysis. Dynamic runtime usage may differ.",
        "Scan results reflect the state of assets at the time of scan upload.",
        "Production migration requires protocol, interoperability, key-management, deployment, and security validation beyond what QShield automates.",
        "Certificate private key material is never extracted, stored, or included in reports.",
    ]:
        story.append(Paragraph(f"• {note}", s["disclaimer"]))
        story.append(Spacer(1, 0.1 * cm))

    doc.build(story)
    return buf.getvalue()


# ═══════════════════════════════════════════════════════════════════════════════
# REPORT 2: Technical Cryptographic Inventory
# ═══════════════════════════════════════════════════════════════════════════════

def build_inventory_pdf(data: dict) -> bytes:
    """
    Build Technical Cryptographic Inventory Report PDF.

    data keys:
      scan, project, dashboard, findings (list of finding dicts),
      risk_summary (dict with per_finding severity)
    """
    buf = io.BytesIO()
    s = _styles()

    dash     = data.get("dashboard", {})
    findings = data.get("findings", [])
    sev_map  = data.get("severity_map", {})   # finding_id -> severity

    project_name = data.get("project", {}).get("name") or dash.get("application_name", "—")
    app_name     = dash.get("application_name", "—")
    scan_name    = dash.get("scan_name", "—")
    gen_ts       = _now_utc()

    on_first, on_later = _make_page_callbacks("Technical Cryptographic Inventory Report", project_name)

    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2.5*cm,
        title="Technical Cryptographic Inventory Report",
        author="QShield",
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame,
                                       onPage=on_first, onPageEnd=on_later)])
    story = []

    # Cover
    story += _cover_flows(
        "Technical Cryptographic\nInventory Report",
        "Cryptographic Bill of Materials (CBOM) — Audit Reference",
        scan_name, project_name, app_name, gen_ts,
    )
    story.append(PageBreak())

    # ── 1. Inventory Statistics ───────────────────────────────────────────────
    story.append(Paragraph("1. Inventory Statistics", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    total = len(findings)
    quantum_vuln = sum(1 for f in findings if f.get("quantum_status") == "vulnerable")
    borderline   = sum(1 for f in findings if f.get("quantum_status") == "borderline")
    safe_count   = sum(1 for f in findings if f.get("quantum_status") in ("safe", "hybrid"))

    stat_data = [
        ["Metric", "Value"],
        ["Total Cryptographic Findings", str(total)],
        ["Quantum-Vulnerable",           str(quantum_vuln)],
        ["Borderline / Transitional",    str(borderline)],
        ["Quantum-Safe",                 str(safe_count)],
    ]
    story.append(_table(stat_data, col_widths=[11*cm, 5*cm]))
    story.append(Spacer(1, 0.4 * cm))

    # ── 2. Algorithm Inventory by Category ───────────────────────────────────
    story.append(Paragraph("2. Algorithm Inventory by Category", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    # Group by category — maps FindingCategory enum string values to display buckets.
    # FindingCategory values (from models/finding.py):
    #   QUANTUM_VULNERABLE_PUBLIC_KEY, SYMMETRIC, HASH, LEGACY_DEPRECATED,
    #   POST_QUANTUM, UNKNOWN_REVIEW
    CRYPTO_CATEGORIES = {
        "public_key":   "Public-Key Cryptography",
        "symmetric":    "Symmetric Cryptography",
        "hash":         "Hash Functions",
        "post_quantum": "Post-Quantum Cryptography",
        "legacy":       "Legacy / Deprecated",
        "other":        "Other / Unknown",
    }
    # Enum value → internal bucket key (covers both uppercase enum strings
    # and any lowercase aliases that may appear in serialised data)
    _CAT_MAP: dict[str, str] = {
        "QUANTUM_VULNERABLE_PUBLIC_KEY": "public_key",
        "SYMMETRIC":                     "symmetric",
        "HASH":                          "hash",
        "POST_QUANTUM":                  "post_quantum",
        "LEGACY_DEPRECATED":             "legacy",
        "UNKNOWN_REVIEW":                "other",
        # lowercase / legacy aliases
        "public_key":   "public_key",
        "symmetric":    "symmetric",
        "hash":         "hash",
        "certificate":  "public_key",
        "configuration": "other",
        "other":        "other",
    }
    by_cat: dict[str, list] = {k: [] for k in CRYPTO_CATEGORIES}
    for f in findings:
        raw_cat = (f.get("category") or "other")
        bucket = _CAT_MAP.get(raw_cat, _CAT_MAP.get(raw_cat.upper(), "other"))
        by_cat[bucket].append(f)


    for cat_key, cat_label in CRYPTO_CATEGORIES.items():
        cat_findings = by_cat.get(cat_key, [])
        if not cat_findings:
            continue
        story.append(Paragraph(cat_label, s["h3"]))

        # group by algorithm within category
        algo_counts: dict[str, dict] = {}
        for f in cat_findings:
            alg = f.get("algorithm", "Unknown")
            if alg not in algo_counts:
                algo_counts[alg] = {
                    "family": f.get("algorithm_family", "—"),
                    "count": 0,
                    "locations": [],
                    "purpose": f.get("usage_context") or "—",
                    "qs": f.get("quantum_status", "unknown"),
                }
            algo_counts[alg]["count"] += 1
            fp = f.get("file_path") or "—"
            if fp not in algo_counts[alg]["locations"] and len(algo_counts[alg]["locations"]) < 3:
                algo_counts[alg]["locations"].append(fp[-40:])

        algo_rows = [["Algorithm", "Family", "Count", "Quantum Status", "Example Location"]]
        algo_extra = []
        for ai, (alg, info) in enumerate(sorted(algo_counts.items()), start=1):
            qs = info["qs"]
            qs_color = {"vulnerable": C_CRIT, "borderline": C_MOD, "safe": C_SAFE, "hybrid": C_SAFE}.get(qs, C_MUTED)
            algo_rows.append([
                alg,
                info["family"],
                str(info["count"]),
                qs.capitalize(),
                info["locations"][0] if info["locations"] else "—",
            ])
            algo_extra.append(("TEXTCOLOR", (3, ai), (3, ai), qs_color))
            algo_extra.append(("FONTNAME",  (3, ai), (3, ai), "Helvetica-Bold"))

        story.append(_table(
            algo_rows,
            col_widths=[3.5*cm, 2.5*cm, 1.5*cm, 2.5*cm, 6*cm],
            extra_style=algo_extra if algo_extra else None,
        ))
        story.append(Spacer(1, 0.3 * cm))

    # ── 3. Quantum Migration Risks (separate from Legacy Security) ────────────
    story.append(PageBreak())
    story.append(Paragraph("3. Quantum Migration Risks", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
    story.append(Paragraph(
        "The following findings represent cryptographic usage that is considered "
        "quantum-vulnerable or borderline. These require active migration planning.",
        s["body"]
    ))
    story.append(Spacer(1, 0.2 * cm))

    qm_findings = [f for f in findings if f.get("quantum_status") in ("vulnerable", "borderline")]
    if qm_findings:
        qm_rows = [["Algorithm", "Status", "Severity", "File", "Line"]]
        qm_extra = []
        for qi, f in enumerate(qm_findings[:40], start=1):  # cap at 40 rows
            sev = sev_map.get(f.get("id", ""), "—")
            fp  = (f.get("file_path") or "—")[-45:]
            ln  = str(f.get("line_number") or "—")
            qs  = f.get("quantum_status", "—")
            qm_rows.append([
                f.get("algorithm", "—"),
                qs.capitalize(),
                sev,
                fp, ln,
            ])
            qm_extra.append(("TEXTCOLOR", (2, qi), (2, qi), _sev_color(sev)))
        story.append(_table(
            qm_rows, col_widths=[3*cm, 2.5*cm, 2.5*cm, 7*cm, 1*cm],
            extra_style=qm_extra if qm_extra else None,
        ))
    else:
        story.append(Paragraph("No quantum-vulnerable or borderline findings identified.", s["body"]))
    story.append(Spacer(1, 0.4 * cm))

    # ── 4. Legacy Security Concerns ───────────────────────────────────────────
    LEGACY_ALGOS = {"md5", "sha1", "sha-1", "rc4", "des", "3des", "triple-des", "rc2"}
    legacy_findings = [
        f for f in findings
        if (f.get("algorithm") or "").lower() in LEGACY_ALGOS
        or (f.get("algorithm_family") or "").lower() in {"md5", "sha1"}
    ]

    story.append(Paragraph("4. Legacy Security Concerns", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
    story.append(Paragraph(
        "The following algorithms are deprecated for classical security reasons (weak key sizes, "
        "known collision vulnerabilities, etc.) independent of quantum threats.",
        s["body"]
    ))
    story.append(Spacer(1, 0.2 * cm))
    if legacy_findings:
        leg_rows = [["Algorithm", "File", "Line", "Usage Context"]]
        for f in legacy_findings[:40]:
            leg_rows.append([
                f.get("algorithm", "—"),
                (f.get("file_path") or "—")[-45:],
                str(f.get("line_number") or "—"),
                (f.get("usage_context") or "—")[:60],
            ])
        story.append(_table(leg_rows, col_widths=[3*cm, 7*cm, 1.5*cm, 4.5*cm]))
    else:
        story.append(Paragraph("No legacy-only algorithm findings identified.", s["body"]))
    story.append(Spacer(1, 0.4 * cm))

    # ── 5. Limitations ────────────────────────────────────────────────────────
    story.append(Paragraph("5. Limitations", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
    for note in [
        "Finding details are based on static analysis of uploaded source code, configuration files, and certificates.",
        "Certificate private key material is never extracted, stored, or included in this report.",
        "Findings are capped at 40 rows per section for readability. Full data available via the Inventory page.",
        "File paths are truncated to 45 characters for display purposes.",
        "Confidence scores reflect the scanner's pattern-match confidence, not an attestation of actual usage.",
    ]:
        story.append(Paragraph(f"• {note}", s["disclaimer"]))
        story.append(Spacer(1, 0.1 * cm))

    doc.build(story)
    return buf.getvalue()


# ═══════════════════════════════════════════════════════════════════════════════
# REPORT 3: Migration Roadmap
# ═══════════════════════════════════════════════════════════════════════════════

def build_roadmap_pdf(data: dict) -> bytes:
    """
    Build Migration Roadmap Report PDF.

    data keys:
      scan, project, dashboard, roadmap (ScanRoadmapResponse dict),
      recommendations (list), top_recs (list)
    """
    buf = io.BytesIO()
    s = _styles()

    dash    = data.get("dashboard", {})
    roadmap = data.get("roadmap", {})
    recs    = data.get("recommendations", [])

    project_name = data.get("project", {}).get("name") or dash.get("application_name", "—")
    app_name     = dash.get("application_name", "—")
    scan_name    = dash.get("scan_name", "—")
    gen_ts       = _now_utc()

    items       = roadmap.get("items", [])
    wave_summ   = roadmap.get("wave_summaries", [])

    on_first, on_later = _make_page_callbacks("Migration Roadmap Report", project_name)

    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2.5*cm,
        title="Migration Roadmap Report",
        author="QShield",
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame,
                                       onPage=on_first, onPageEnd=on_later)])
    story = []

    # Cover
    story += _cover_flows(
        "Migration Roadmap Report",
        "Post-Quantum Cryptography Migration Plan",
        scan_name, project_name, app_name, gen_ts,
    )
    story.append(PageBreak())

    # ── 1. Migration Overview ─────────────────────────────────────────────────
    story.append(Paragraph("1. Migration Overview", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    total_items = len(items)
    migrated    = sum(1 for it in items if it.get("stage") == "MIGRATED")
    prog        = dash.get("migration_progress_pct", 0.0)
    qrs         = dash.get("quantum_readiness_score", 0)

    ov_data = [
        ["Metric", "Value"],
        ["Total Roadmap Items", str(total_items)],
        ["Migrated",            str(migrated)],
        ["Migration Progress",  f"{prog:.1f}%"],
        ["Quantum Readiness Score", f"{qrs}/100 ({dash.get('readiness_label', '—')})"],
    ]
    story.append(_table(ov_data, col_widths=[11*cm, 5*cm]))
    story.append(Spacer(1, 0.4 * cm))

    # ── 2. Wave Summary ───────────────────────────────────────────────────────
    if wave_summ:
        story.append(Paragraph("2. Migration Waves", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

        WAVE_LABELS = {1: "NOW — Immediate priorities", 2: "NEXT — Near-term work", 3: "LATER — Planned work"}
        for ws in sorted(wave_summ, key=lambda x: x.get("wave", 99)):
            wn = ws.get("wave", "?")
            story.append(Paragraph(f"Wave {wn}: {WAVE_LABELS.get(wn, '')}", s["h3"]))
            story.append(Paragraph(ws.get("description", ""), s["body"]))
            w_data = [["Metric", "Value"],
                      ["Total Items", str(ws.get("item_count", ws.get("total_items", 0)))]]
            story.append(_table(w_data, col_widths=[8*cm, 8*cm]))
            story.append(Spacer(1, 0.2 * cm))

    # ── 3. Lifecycle Stage Distribution ───────────────────────────────────────
    stage_dist = dash.get("stage_distribution", [])
    if stage_dist:
        story.append(Paragraph("3. Lifecycle Stage Distribution", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
        stg_rows = [["Stage", "Items", "Description"]]
        STAGE_DESC = {
            "DISCOVERED": "Finding catalogued",
            "ASSESSED":   "Risk and impact evaluated",
            "PLANNED":    "Migration approach selected",
            "PILOT":      "In controlled pilot",
            "TRANSITION": "Active migration in progress",
            "VALIDATION": "Security validation in progress",
            "MIGRATED":   "Migration complete",
        }
        for st in stage_dist:
            nm = st.get("stage", "—")
            stg_rows.append([nm, str(st.get("count", 0)), STAGE_DESC.get(nm, "—")])
        story.append(_table(stg_rows, col_widths=[4*cm, 2*cm, 10*cm]))
        story.append(Spacer(1, 0.4 * cm))

    # ── 4. Roadmap Items by Wave ──────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("4. Roadmap Items Detail", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))

    for wave_num in [1, 2, 3]:
        wave_items = [it for it in items if it.get("wave") == wave_num]
        if not wave_items:
            continue
        story.append(Paragraph(f"Wave {wave_num} Items", s["h3"]))
        rd_rows = [["Algorithm", "Stage", "Effort", "Target", "File"]]
        for it in wave_items[:30]:  # cap per wave
            rd_rows.append([
                it.get("algorithm", "—"),
                it.get("stage", "DISCOVERED"),
                it.get("effort_estimate", "—"),
                it.get("recommended_target_category", "—"),
                (it.get("file_path") or "—")[-40:],
            ])
        story.append(_table(rd_rows, col_widths=[3*cm, 2.5*cm, 2*cm, 4*cm, 4.5*cm]))
        story.append(Spacer(1, 0.3 * cm))

    # ── 5. Priority Actions ───────────────────────────────────────────────────
    quantum_recs = [r for r in recs if r.get("is_quantum_concern")][:5]
    if quantum_recs:
        story.append(Paragraph("5. Priority Actions", s["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
        for i, r in enumerate(quantum_recs, 1):
            algo = r.get("algorithm", "—")
            tgt  = r.get("recommended_target_category", "—")
            prio = r.get("migration_priority", "low").upper()
            stds = ", ".join(r.get("nist_standards", [])) or "—"
            story.append(KeepTogether([
                Paragraph(f"{i}. {algo} → {tgt}  [Priority: {prio}  |  NIST: {stds}]", s["h3"]),
                Paragraph(r.get("quantum_threat", ""), s["body"]),
                Spacer(1, 0.2 * cm),
            ]))

    # ── 6. Limitations ────────────────────────────────────────────────────────
    story.append(Paragraph("6. Limitations", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_ACCENT, spaceAfter=6))
    for note in [
        "Roadmap wave assignment is deterministic — derived from risk score and application context.",
        "User-controlled lifecycle stages (ASSESSED, PLANNED, etc.) are persisted and reflected here.",
        "Migration effort estimates are indicative — actual effort depends on codebase complexity and team capacity.",
        "Timeline guidance is advisory only and not a project plan commitment.",
        "QShield does not automatically perform migration. All changes require developer implementation and security review.",
    ]:
        story.append(Paragraph(f"• {note}", s["disclaimer"]))
        story.append(Spacer(1, 0.1 * cm))

    doc.build(story)
    return buf.getvalue()
