/**
 * RecommendationsPage.tsx — QShield Migration Recommendations
 *
 * Displays deterministic, purpose-aware migration recommendations
 * generated by the backend KB engine. All content from backend — nothing hardcoded.
 *
 * Design: Light enterprise SaaS — matches RiskPage and InventoryPage.
 *
 * Route: /recommendations/:scanId
 */
import { useEffect, useState, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import {
  ArrowLeft, RefreshCw, AlertTriangle, CheckCircle,
  HelpCircle, Info, ChevronDown, ChevronUp,
  Home, BookOpen, BarChart2, Map, FlaskConical, FileText, Clock,
  Shield, AlertCircle, ChevronRight,
} from 'lucide-react';
import QShieldLogo from '../components/QShieldLogo';
import { getRecommendations } from '../services/recommendationsApi';
import type { ScanRecommendationResult, MigrationRecommendation } from '../services/recommendationsApi';

// ── Design tokens (identical to RiskPage) ────────────────────────────────────

const BORDER  = '1px solid rgba(25,40,55,0.09)';
const BORDER2 = '1px solid rgba(25,40,55,0.06)';
const TEXT    = '#192837';
const MUTED   = 'rgba(25,40,55,0.45)';
const MUTED2  = 'rgba(25,40,55,0.30)';
const BG_PAGE = '#f8f8f5';
const BG_SURF = '#ffffff';
const ACCENT  = '#7342E2';

// ── Effort badge colours ──────────────────────────────────────────────────────

const EFFORT_CFG: Record<string, { bg: string; text: string; border: string }> = {
  low:      { bg: '#f0fdf4', text: '#15803d', border: '#bbf7d0' },
  medium:   { bg: '#fffbeb', text: '#92400e', border: '#fde68a' },
  high:     { bg: '#fff7ed', text: '#c2410c', border: '#fed7aa' },
  very_high:{ bg: '#fef2f2', text: '#b91c1c', border: '#fecaca' },
  unknown:  { bg: '#f9fafb', text: '#374151', border: '#e5e7eb' },
};
const getEffort = (e: string) => EFFORT_CFG[e] ?? EFFORT_CFG.unknown;

// ── Priority colour ───────────────────────────────────────────────────────────

const PRI_COLOR: Record<string, string> = {
  immediate: '#b91c1c',
  near_term: '#c2410c',
  long_term: '#a16207',
  low:       '#15803d',
};
const getPriColor = (p: string | null) => PRI_COLOR[p ?? ''] ?? MUTED;
const PRI_LABEL: Record<string, string> = {
  immediate: 'Immediate',
  near_term: 'Near Term',
  long_term: 'Long Term',
  low:       'Low Priority',
};

// ── Purpose display labels ────────────────────────────────────────────────────

const PURPOSE_LABEL: Record<string, string> = {
  key_establishment:    'Key Establishment / KEM',
  digital_signature:    'Digital Signature',
  symmetric_encryption: 'Symmetric Encryption',
  hashing:              'Hashing',
  mac:                  'Message Authentication (MAC)',
  key_derivation:       'Key Derivation',
  certificate:          'Certificate / PKI',
  encryption:           'Asymmetric Encryption',
  unknown:              'Unknown — Manual Review Required',
};

// ── Sidebar (matches RiskPage) ────────────────────────────────────────────────

function Sidebar({ scanId }: { scanId?: string }) {
  const navItems = [
    { key: 'overview',      label: 'Overview',        Icon: Home,         to: '/app/dashboard' },
    { key: 'inventory',     label: 'Crypto Inventory', Icon: BookOpen,     to: scanId ? `/inventory/${scanId}` : '/upload' },
    { key: 'risk',          label: 'Risk Analysis',    Icon: BarChart2,    to: scanId ? `/risk/${scanId}` : '#' },
    { key: 'migration',     label: 'Migration',        Icon: Map,          to: scanId ? `/recommendations/${scanId}` : '#', active: true },
    { key: 'roadmap',       label: 'Roadmap',          Icon: Clock,        to: scanId ? `/roadmap/${scanId}` : '#' },
    { key: 'pqclab',        label: 'PQC Lab',          Icon: FlaskConical, to: '/demo' },
    { key: 'reports',       label: 'Reports',          Icon: FileText,     to: '#' },
  ];
  return (
    <aside style={{
      width: 220, flexShrink: 0, background: BG_SURF, borderRight: BORDER,
      display: 'flex', flexDirection: 'column', minHeight: '100vh',
      position: 'sticky', top: 0, alignSelf: 'flex-start',
    }}>
      <div style={{ padding: '18px 20px 16px', borderBottom: BORDER, display: 'flex', alignItems: 'center', gap: 10 }}>
        <QShieldLogo size={20} color={TEXT} />
        <span style={{ fontSize: 15, fontWeight: 700, fontFamily: 'var(--font-heading)', color: TEXT, letterSpacing: '-0.01em' }}>
          QShield
        </span>
      </div>
      <nav style={{ padding: '10px 10px', flex: 1 }}>
        {navItems.map(({ key, label, Icon, to, active }) => {
          const isDisabled = to === '#';
          return (
            <Link key={key} to={to} style={{
              display: 'flex', alignItems: 'center', gap: 10,
              padding: '7px 12px', borderRadius: 7, marginBottom: 1,
              fontSize: 13, fontWeight: active ? 600 : 400,
              color: active ? ACCENT : isDisabled ? MUTED2 : TEXT,
              background: active ? `${ACCENT}10` : 'transparent',
              textDecoration: 'none', opacity: isDisabled ? 0.5 : 1,
              cursor: isDisabled ? 'default' : 'pointer',
              pointerEvents: isDisabled ? 'none' : 'auto',
            }}
              onMouseEnter={e => { if (!active && !isDisabled) (e.currentTarget as HTMLAnchorElement).style.background = 'rgba(25,40,55,0.04)'; }}
              onMouseLeave={e => { if (!active && !isDisabled) (e.currentTarget as HTMLAnchorElement).style.background = 'transparent'; }}
            >
              <span style={{ color: active ? ACCENT : MUTED, flexShrink: 0 }}><Icon size={15} /></span>
              {label}
            </Link>
          );
        })}
      </nav>
      <div style={{ padding: '14px 20px', borderTop: BORDER }}>
        <span style={{ fontSize: 11, color: MUTED2 }}>QShield · KB v{scanId ? '1.0' : '—'}</span>
      </div>
    </aside>
  );
}

// ── Summary strip ─────────────────────────────────────────────────────────────

function SummaryStrip({ data }: { data: ScanRecommendationResult }) {
  const items = [
    { label: 'Total Findings', value: String(data.total_findings), color: TEXT,      icon: null },
    { label: 'Quantum Concerns', value: String(data.quantum_concern_count), color: '#b91c1c', icon: <AlertCircle size={13} /> },
    { label: 'Classical / Legacy', value: String(data.classical_only_count), color: '#c2410c', icon: <AlertTriangle size={13} /> },
    { label: 'Already Safe', value: String(data.safe_count), color: '#15803d', icon: <CheckCircle size={13} /> },
    { label: 'Manual Review', value: String(data.manual_review_count), color: '#a16207', icon: <HelpCircle size={13} /> },
  ];
  return (
    <div style={{ background: BG_SURF, border: BORDER, borderRadius: 10, display: 'flex', alignItems: 'stretch', overflow: 'hidden' }}>
      {items.map((item, i) => (
        <div key={item.label} style={{
          flex: 1, padding: '12px 18px', borderRight: i < items.length - 1 ? BORDER : 'none',
          display: 'flex', flexDirection: 'column', gap: 2, minWidth: 0,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            {item.icon && <span style={{ color: item.color }}>{item.icon}</span>}
            <span style={{ fontSize: 11, color: MUTED, fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              {item.label}
            </span>
          </div>
          <div style={{ fontSize: 22, fontWeight: 700, color: item.color, fontFamily: 'var(--font-heading)', lineHeight: 1.1 }}>
            {item.value}
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Recommendation row (expandable) ──────────────────────────────────────────

function RecommendationRow({
  rec,
  scanId,
  isLast,
}: {
  rec: MigrationRecommendation;
  scanId: string;
  isLast: boolean;
}) {
  const [open, setOpen] = useState(false);
  const effortCfg = getEffort(rec.effort_estimate);
  const priColor  = getPriColor(rec.migration_priority);
  const priLabel  = PRI_LABEL[rec.migration_priority ?? ''] ?? '—';
  const purposeLabel = PURPOSE_LABEL[rec.crypto_purpose] ?? rec.crypto_purpose;

  // Row accent colour
  const rowBorderLeft = rec.requires_manual_review
    ? '3px solid #f59e0b'
    : rec.is_quantum_concern
      ? '3px solid #ef4444'
      : '3px solid #22c55e';

  return (
    <>
      {/* Summary row */}
      <div
        onClick={() => setOpen(o => !o)}
        style={{
          display: 'grid',
          gridTemplateColumns: '3px 1fr 140px 110px 80px 28px',
          alignItems: 'center',
          cursor: 'pointer',
          borderBottom: !open && !isLast ? BORDER2 : 'none',
          transition: 'background 0.1s',
        }}
        onMouseEnter={e => { (e.currentTarget as HTMLElement).style.background = 'rgba(25,40,55,0.02)'; }}
        onMouseLeave={e => { (e.currentTarget as HTMLElement).style.background = 'transparent'; }}
      >
        {/* Left accent bar */}
        <div style={{ alignSelf: 'stretch', background: rowBorderLeft.split(' ')[2] }} />

        {/* Main info */}
        <div style={{ padding: '10px 14px', minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            <span style={{ fontWeight: 600, color: TEXT, fontSize: 13 }}>{rec.algorithm}</span>
            <span style={{ fontSize: 11, color: MUTED, background: 'rgba(25,40,55,0.06)', padding: '1px 6px', borderRadius: 4 }}>
              {rec.algorithm_family}
            </span>
            {rec.requires_manual_review && (
              <span style={{ fontSize: 10, fontWeight: 600, color: '#92400e', background: '#fffbeb', border: '1px solid #fde68a', padding: '1px 6px', borderRadius: 4 }}>
                MANUAL REVIEW
              </span>
            )}
          </div>
          <div style={{ fontSize: 11, color: MUTED, marginTop: 2 }}>
            {purposeLabel}
            {rec.file_path && (
              <> &nbsp;·&nbsp; <span style={{ fontFamily: 'monospace' }}>{rec.file_path}</span></>
            )}
          </div>
        </div>

        {/* Target category */}
        <div style={{ padding: '10px 8px', fontSize: 11, color: TEXT, lineHeight: 1.4, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {rec.recommended_target_category}
        </div>

        {/* Priority */}
        <div style={{ padding: '10px 8px', fontSize: 11, fontWeight: 600, color: priColor, whiteSpace: 'nowrap' }}>
          {priLabel}
        </div>

        {/* Effort */}
        <div style={{ padding: '10px 8px' }}>
          <span style={{
            fontSize: 10, fontWeight: 600,
            background: effortCfg.bg, color: effortCfg.text, border: `1px solid ${effortCfg.border}`,
            borderRadius: 5, padding: '2px 6px', whiteSpace: 'nowrap',
          }}>
            {rec.effort_estimate.replace('_', '-')}
          </span>
        </div>

        {/* Chevron */}
        <div style={{ padding: '10px 8px', color: MUTED2, flexShrink: 0 }}>
          {open ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </div>
      </div>

      {/* Expanded detail */}
      {open && (
        <div style={{
          padding: '0 20px 16px 20px',
          borderBottom: isLast ? 'none' : BORDER2,
          background: 'rgba(25,40,55,0.012)',
        }}>
          {/* Purpose + confidence */}
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 14, paddingTop: 10 }}>
            <InfoPill label="Purpose" value={purposeLabel} accent={rec.requires_manual_review ? '#a16207' : ACCENT} />
            <InfoPill
              label="Confidence"
              value={rec.requires_manual_review
                ? 'Manual review required'
                : `${Math.round(rec.purpose_confidence * 100)}%`}
              accent={rec.requires_manual_review ? '#a16207' : '#15803d'}
            />
            {rec.migration_priority && (
              <InfoPill label="Migration Priority" value={priLabel} accent={priColor} />
            )}
            {rec.quantum_migration_score != null && (
              <InfoPill label="Risk Score (Part 7)" value={`${rec.quantum_migration_score.toFixed(1)}/100`} accent={TEXT} />
            )}
          </div>

          {/* Current state */}
          <Section title="Current State">
            <div style={{ fontSize: 12, color: TEXT, lineHeight: 1.65 }}>
              {rec.current_state_description}
            </div>
          </Section>

          {/* Quantum threat / reason for concern */}
          <Section title={rec.is_quantum_concern ? 'Quantum Threat' : 'Reason for Concern'}>
            <div style={{
              fontSize: 12, color: rec.is_quantum_concern ? '#b91c1c' : '#92400e',
              background: rec.is_quantum_concern ? '#fef2f2' : '#fffbeb',
              border: `1px solid ${rec.is_quantum_concern ? '#fecaca' : '#fde68a'}`,
              borderRadius: 7, padding: '10px 14px', lineHeight: 1.65,
            }}>
              {rec.quantum_threat}
            </div>
          </Section>

          {/* Purpose reasoning */}
          <Section title="Purpose Classification">
            <div style={{ fontSize: 12, color: MUTED, lineHeight: 1.6, fontStyle: 'italic' }}>
              {rec.purpose_reasoning}
            </div>
          </Section>

          {/* Target + algorithms */}
          {!rec.requires_manual_review && rec.recommended_algorithms.length > 0 && (
            <Section title="Recommended Target">
              <div style={{ fontSize: 12, fontWeight: 600, color: ACCENT, marginBottom: 8 }}>
                {rec.recommended_target_category}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                {rec.recommended_algorithms.map((a, i) => (
                  <div key={i} style={{
                    fontSize: 12, color: TEXT,
                    background: BG_SURF, border: BORDER,
                    borderRadius: 6, padding: '6px 10px',
                    display: 'flex', alignItems: 'flex-start', gap: 8,
                  }}>
                    <Shield size={12} style={{ color: ACCENT, flexShrink: 0, marginTop: 1 }} />
                    {a}
                  </div>
                ))}
              </div>
              {rec.nist_standards.length > 0 && (
                <div style={{ marginTop: 8, fontSize: 11, color: MUTED2 }}>
                  NIST: {rec.nist_standards.join(' · ')}
                </div>
              )}
            </Section>
          )}

          {/* Prerequisites */}
          {rec.prerequisites.length > 0 && (
            <Section title="Prerequisites">
              <OrderedList items={rec.prerequisites} bullet="•" />
            </Section>
          )}

          {/* Migration steps */}
          {rec.migration_steps.length > 0 && (
            <Section title="Migration Steps">
              <OrderedList items={rec.migration_steps} />
            </Section>
          )}

          {/* Testing requirements */}
          {rec.testing_requirements.length > 0 && (
            <Section title="Testing Requirements">
              <OrderedList items={rec.testing_requirements} bullet="•" />
            </Section>
          )}

          {/* Interoperability */}
          {rec.interoperability_notes.length > 0 && (
            <Section title="Compatibility & Interoperability">
              <OrderedList items={rec.interoperability_notes} bullet="⚠" bulletColor="#c2410c" />
            </Section>
          )}

          {/* Timeline */}
          {rec.timeline_guidance && (
            <Section title="Timeline Guidance">
              <div style={{ fontSize: 12, color: MUTED, lineHeight: 1.6 }}>{rec.timeline_guidance}</div>
            </Section>
          )}

          {/* Technical notes */}
          {rec.technical_notes && (
            <Section title="Technical Notes">
              <div style={{
                fontSize: 12, color: '#1e40af', background: '#eff6ff',
                border: '1px solid #bfdbfe', borderRadius: 7,
                padding: '10px 14px', lineHeight: 1.65,
              }}>
                {rec.technical_notes}
              </div>
            </Section>
          )}

          {/* Validation checklist */}
          {rec.validation_checklist.length > 0 && (
            <Section title="Validation Checklist">
              <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                {rec.validation_checklist.map((item, i) => (
                  <div key={i} style={{ fontSize: 12, color: TEXT, display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                    <span style={{ color: ACCENT, flexShrink: 0, marginTop: 1 }}>□</span>
                    {item.replace(/^\[ ?\] /, '')}
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* KB provenance + finding link */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 }}>
            <span style={{ fontSize: 11, color: MUTED2 }}>
              KB {rec.kb_version}
              {rec.kb_entry_key && <> · {rec.kb_entry_key}</>}
            </span>
            <Link
              to={`/inventory/${scanId}/finding/${rec.finding_id}`}
              style={{ fontSize: 12, color: ACCENT, textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 4 }}
            >
              View finding detail <ChevronRight size={12} />
            </Link>
          </div>
        </div>
      )}
    </>
  );
}

// ── Shared sub-components ─────────────────────────────────────────────────────

function InfoPill({ label, value, accent }: { label: string; value: string; accent: string }) {
  return (
    <div style={{
      background: BG_SURF, border: BORDER, borderRadius: 7, padding: '5px 12px',
      display: 'flex', flexDirection: 'column', gap: 1,
    }}>
      <span style={{ fontSize: 10, color: MUTED2, textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>{label}</span>
      <span style={{ fontSize: 12, fontWeight: 600, color: accent }}>{value}</span>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 12 }}>
      <div style={{ fontSize: 10, fontWeight: 600, color: MUTED2, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 5 }}>
        {title}
      </div>
      {children}
    </div>
  );
}

function OrderedList({
  items,
  bullet = '',
  bulletColor = MUTED,
}: {
  items: string[];
  bullet?: string;
  bulletColor?: string;
}) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
      {items.map((item, i) => (
        <div key={i} style={{ fontSize: 12, color: TEXT, display: 'flex', gap: 8, alignItems: 'flex-start', lineHeight: 1.5 }}>
          <span style={{ color: bulletColor, flexShrink: 0, minWidth: 12 }}>{bullet || `${i + 1}.`}</span>
          <span>{bullet ? item : item.replace(/^\d+\.\s*/, '')}</span>
        </div>
      ))}
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function RecommendationsPage() {
  const { scanId } = useParams<{ scanId: string }>();
  const navigate = useNavigate();

  const [data, setData] = useState<ScanRecommendationResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'quantum' | 'manual' | 'safe'>('all');

  const load = useCallback(async () => {
    if (!scanId) return;
    setLoading(true);
    setError(null);
    try {
      setData(await getRecommendations(scanId));
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load recommendations');
    } finally {
      setLoading(false);
    }
  }, [scanId]);

  useEffect(() => { load(); }, [load]);

  // ── Loading ───────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div style={{ display: 'flex', minHeight: '100dvh', background: BG_PAGE }}>
        <Sidebar scanId={scanId} />
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: 14 }}>
          <div style={{
            width: 36, height: 36, borderRadius: '50%',
            border: `2px solid ${ACCENT}30`, borderTopColor: ACCENT,
            animation: 'spin 0.8s linear infinite',
          }} />
          <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
          <span style={{ fontSize: 13, color: MUTED }}>Generating recommendations…</span>
        </div>
      </div>
    );
  }

  // ── Error ─────────────────────────────────────────────────────────────────
  if (error) {
    return (
      <div style={{ display: 'flex', minHeight: '100dvh', background: BG_PAGE }}>
        <Sidebar scanId={scanId} />
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 32 }}>
          <div style={{
            background: BG_SURF, border: '1px solid #fecaca', borderRadius: 12,
            padding: 32, maxWidth: 440, textAlign: 'center',
          }}>
            <AlertTriangle size={32} style={{ color: '#ef4444', margin: '0 auto 12px', display: 'block' }} />
            <div style={{ fontSize: 15, fontWeight: 600, color: TEXT, marginBottom: 8 }}>Recommendations Failed</div>
            <div style={{ fontSize: 13, color: MUTED, marginBottom: 20 }}>{error}</div>
            <div style={{ display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button onClick={load} style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '7px 16px', borderRadius: 7, border: BORDER,
                background: BG_SURF, fontSize: 13, cursor: 'pointer', color: TEXT,
              }}>
                <RefreshCw size={13} /> Retry
              </button>
              <button onClick={() => navigate(`/risk/${scanId}`)} style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '7px 16px', borderRadius: 7, border: 'none',
                background: ACCENT, fontSize: 13, cursor: 'pointer', color: 'white', fontWeight: 600,
              }}>
                <BarChart2 size={13} /> Risk Analysis
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!data) return null;

  // ── Filter recommendations ────────────────────────────────────────────────
  const visible = data.recommendations.filter(r => {
    if (filter === 'quantum') return r.is_quantum_concern;
    if (filter === 'manual')  return r.requires_manual_review;
    if (filter === 'safe')    return !r.is_quantum_concern && !r.requires_manual_review;
    return true;
  });

  const FILTERS = [
    { id: 'all',     label: `All (${data.total_findings})` },
    { id: 'quantum', label: `Quantum (${data.quantum_concern_count})` },
    { id: 'safe',    label: `Safe / Low (${data.safe_count})` },
    { id: 'manual',  label: `Review (${data.manual_review_count})` },
  ] as const;

  return (
    <div style={{ display: 'flex', minHeight: '100dvh', background: BG_PAGE, fontFamily: 'var(--font-body)', color: TEXT }}>
      <Sidebar scanId={scanId} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>

        {/* ── Top header ── */}
        <div style={{
          background: BG_SURF, borderBottom: BORDER, padding: '0 28px',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          height: 56, position: 'sticky', top: 0, zIndex: 10,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 16, fontWeight: 700, fontFamily: 'var(--font-heading)', color: TEXT }}>
              Migration Recommendations
            </span>
            {scanId && (
              <>
                <span style={{ color: MUTED2, fontSize: 16 }}>/</span>
                <span style={{ fontSize: 12, color: MUTED, fontFamily: 'monospace', maxWidth: 240, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {scanId}
                </span>
              </>
            )}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <button onClick={load} style={{
              display: 'flex', alignItems: 'center', gap: 5, padding: '5px 10px',
              borderRadius: 7, border: BORDER, background: 'transparent',
              fontSize: 12, cursor: 'pointer', color: MUTED,
            }}>
              <RefreshCw size={12} /> Refresh
            </button>
            <button onClick={() => navigate(`/risk/${scanId}`)} style={{
              display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px',
              borderRadius: 7, border: BORDER, background: 'transparent',
              fontSize: 13, cursor: 'pointer', color: TEXT, fontWeight: 500,
            }}>
              <BarChart2 size={13} /> Risk Analysis
            </button>
            <button onClick={() => navigate(`/inventory/${scanId}`)} style={{
              display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px',
              borderRadius: 7, border: BORDER, background: 'transparent',
              fontSize: 13, cursor: 'pointer', color: TEXT, fontWeight: 500,
            }}>
              <ArrowLeft size={13} /> Inventory
            </button>
            {scanId && (
              <button onClick={() => navigate(`/roadmap/${scanId}`)} style={{
                display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px',
                borderRadius: 7, border: `1px solid ${ACCENT}40`, background: `${ACCENT}08`,
                fontSize: 13, cursor: 'pointer', color: ACCENT, fontWeight: 600,
              }}>
                <Clock size={13} /> Roadmap
              </button>
            )}
          </div>
        </div>

        {/* ── Page body ── */}
        <div style={{ padding: '24px 28px', display: 'flex', flexDirection: 'column', gap: 20 }}>

          {/* KB version + summary */}
          <div style={{
            display: 'flex', gap: 10, alignItems: 'flex-start',
            background: '#f5f3ff', border: '1px solid #ede9fe',
            borderRadius: 8, padding: '10px 14px',
            fontSize: 12, color: '#4c1d95',
          }}>
            <Info size={14} style={{ flexShrink: 0, marginTop: 1 }} />
            <span>
              <strong>QShield Migration Knowledge Base v{data.kb_version}</strong> — {data.summary}
              {' '}Recommendations are deterministic. No LLM is used.
            </span>
          </div>

          {/* Summary strip */}
          <SummaryStrip data={data} />

          {/* Filter tabs */}
          <div style={{ background: BG_SURF, border: BORDER, borderRadius: 10, overflow: 'hidden' }}>
            {/* Tab bar */}
            <div style={{ borderBottom: BORDER, padding: '0 16px', display: 'flex', gap: 0 }}>
              {FILTERS.map(f => (
                <button
                  key={f.id}
                  onClick={() => setFilter(f.id)}
                  style={{
                    padding: '9px 16px', fontSize: 12, fontWeight: filter === f.id ? 600 : 400,
                    color: filter === f.id ? ACCENT : MUTED,
                    background: 'none', border: 'none', cursor: 'pointer',
                    borderBottom: filter === f.id ? `2px solid ${ACCENT}` : '2px solid transparent',
                    marginBottom: -1,
                  }}
                >
                  {f.label}
                </button>
              ))}
            </div>

            {/* Column headers */}
            {visible.length > 0 && (
              <div style={{
                display: 'grid',
                gridTemplateColumns: '3px 1fr 140px 110px 80px 28px',
                padding: '6px 0',
                borderBottom: BORDER,
                fontSize: 10, fontWeight: 600,
                color: MUTED2, textTransform: 'uppercase', letterSpacing: '0.06em',
              }}>
                <div />
                <div style={{ padding: '0 14px' }}>Algorithm / Purpose</div>
                <div style={{ padding: '0 8px' }}>Target</div>
                <div style={{ padding: '0 8px' }}>Priority</div>
                <div style={{ padding: '0 8px' }}>Effort</div>
                <div />
              </div>
            )}

            {/* Recommendation rows */}
            {visible.length === 0 ? (
              <div style={{ padding: '40px 20px', textAlign: 'center' }}>
                <CheckCircle size={32} style={{ color: '#22c55e', margin: '0 auto 12px', display: 'block' }} />
                <div style={{ fontSize: 14, fontWeight: 600, color: TEXT, marginBottom: 6 }}>
                  No recommendations in this category
                </div>
                <div style={{ fontSize: 13, color: MUTED }}>
                  {filter === 'all' ? 'No findings were detected.' : 'Try a different filter.'}
                </div>
              </div>
            ) : (
              visible.map((rec, i) => (
                <RecommendationRow
                  key={rec.finding_id}
                  rec={rec}
                  scanId={scanId!}
                  isLast={i === visible.length - 1}
                />
              ))
            )}
          </div>

          {/* Footer */}
          <div style={{ fontSize: 11, color: MUTED2, textAlign: 'center', paddingBottom: 16, lineHeight: 1.5 }}>
            QShield Migration Knowledge Base v{data.kb_version} — Deterministic recommendations. Not an official NIST score.
            Consult a cryptography expert before executing migration plans.
          </div>
        </div>
      </div>
    </div>
  );
}
